repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
      - id: gradle-task
        args: [ '-w', 'ktlintFormat' ]
      - id: gradle-task
        args: [ '-w', 'ktlintCheck' ]
      - id: gradle-task
        args: [ '-w', 'detekt' ]
