name: Backend Pull Request

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  check:
    name: Check Gradle
    uses: ./.github/workflows/gradle-check.yaml
